# In this notebook we will look into the basics of Tensorflow including its syntax, graphs placeholders etc..

In [2]:
import tensorflow as tf 

In [3]:
print(tf.__version__)  # version check

1.8.0


In [4]:
# creating constants 
hello = tf.constant('Hello ')

In [5]:
world = tf.constant('World ')

In [7]:
type(hello) # this shows hello and world are tensor objects

tensorflow.python.framework.ops.Tensor

In [8]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [9]:
# to print a tensor we build a session
with tf.Session() as sess:
    result =sess.run(hello + world)

In [10]:
result

b'Hello World '

In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
with tf.Session() as sess:
    res =sess.run(a + b)

In [16]:
res

30

In [17]:
const = tf.constant(10)


In [18]:
fill_mat = tf.fill((4,4),10)   #Creates a tensor filled with a scalar value.

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)  # Outputs random values from a normal distribution.

In [22]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)  # Outputs random values from a uniform distribution.

In [23]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]  # tensor

In [24]:
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.45185846  1.3215532  -0.08210689  0.09180323]
 [ 0.7629687   0.57327473 -0.1967189  -0.22034262]
 [ 0.07281801  0.46574566 -0.5510643   0.06880397]
 [ 0.6420655   0.659983   -0.3689758  -0.43757427]]


[[0.70009005 0.17576575 0.91652215 0.21725798]
 [0.9577764  0.09629583 0.47399998 0.20538676]
 [0.8943114  0.7311901  0.9472269  0.40953147]
 [0.91011393 0.63276947 0.8892113  0.30624235]]




In [26]:
a = tf.constant([ [1,2],
                  [3,4] ])   # 2 by 2 matrix or tensor

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([[10],[100]])

In [29]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [30]:
result = tf.matmul(a,b)

In [31]:
result.eval()

array([[210],
       [430]])