In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


In [3]:
# creating Tensors - N dimensional array
# create constant
# tf.constant supports Tensor values

Hello = tf.constant("Hello ")

In [4]:
World = tf.constant("World !!")

In [5]:
type(Hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(Hello)    # does not print a string rather it is a tensor

Tensor("Const:0", shape=(), dtype=string)


In [7]:
# Creating session in tensorflow to access string

with tf.Session() as sess:
    result = sess.run(Hello + World)     # concatinating strings
    # He = sess.run(Hello)

In [8]:
print(result)              

b'Hello World !!'


b represents byte

In [9]:
# Numeric Tensors
a = tf.constant(10)
b= tf.constant(2)


In [10]:
type(a)


tensorflow.python.framework.ops.Tensor

In [11]:
print(a + b)      # does not work

Tensor("add_1:0", shape=(), dtype=int32)


In [12]:
with tf.Session() as sess:
    output = sess.run(a+b)

In [13]:
output

12

In [14]:
const = tf.constant(10)     # creating a constant tensor

In [15]:
with tf.Session() as sess:
    out = sess.run(const)

In [16]:
print(out)

10


In [17]:
# Creates a tensor filled with a scalar value

fill_mat = tf.fill([2,2],9)

In [18]:
fill_mat

<tf.Tensor 'Fill:0' shape=(2, 2) dtype=int32>

In [19]:
print(fill_mat)

Tensor("Fill:0", shape=(2, 2), dtype=int32)


In [20]:
with tf.Session() as sess:
    output = sess.run(fill_mat)
    

In [21]:
output

array([[9, 9],
       [9, 9]])

In [22]:
myzeros = tf.zeros((4,4))

In [23]:
myones = tf.ones((4,4))

In [24]:
with tf.Session() as sess:
    output = sess.run(myzeros)
    result = sess.run(myones)

In [25]:
print(output)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# creating random distributions and uniform distribution

myrandn = tf.random_normal((4,4), mean= 0,stddev = 1.0)

In [28]:
myrandu = tf.random_uniform((4,4),minval =0,maxval= 1)

In [29]:
# creating a list of all tensors declared above to be called simulateneously

my_ops =[const,fill_mat,myones,myzeros,myrandn,myrandu]

#A TensorFlow Session for use in interactive contexts, such as a shell.

The only difference with a regular Session is that an InteractiveSession installs itself as the default session on construction

In [48]:
# Intro to Intractive Session

sess = tf.InteractiveSession()

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\client\session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [49]:
# creating session to print out result of all tensors created

for op in my_ops:
    print(sess.run(op))     # or print(op.eval())
    print('\n')

10


[[9 9]
 [9 9]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.97110677  1.4847478   3.5209436  -0.71972436]
 [-1.369543   -1.8387363  -0.3787699   1.7425984 ]
 [-0.40091267 -0.52651274 -0.67936033 -2.2244995 ]
 [ 0.6467244  -0.5974083   1.9533801   0.76639545]]


[[0.983312   0.07608688 0.0998013  0.6923659 ]
 [0.54373634 0.88461757 0.9629555  0.05354559]
 [0.51371944 0.8797463  0.6159593  0.38022518]
 [0.38597393 0.67185473 0.07250512 0.10721183]]




In [50]:
# Can work like this as well

# with tf.Session() as sess:
#    GOUT = sess.run(my_ops)
#    print('\n')
#    print(GOUT)
#    print('\n')

In [51]:
# Matrix multiplication
# creating a constant tensor of nested list

a = tf.constant([[1,2],              # [1  2]
                [3,4]])              # [3  4]

In [52]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [53]:
b = tf.constant([[10],[100]])       # [10 ]
                                    # [100]

In [54]:
b.get_shape()  

TensorShape([Dimension(2), Dimension(1)])

In [55]:
result= tf.matmul(a,b)

In [56]:
sess.run(result)     # can run outside a session because we called an interactive session at the top

array([[210],
       [430]])

In [58]:
result.eval()      # can work this way too

array([[210],
       [430]])